// src/components/NavBar.svelte
<script type="ts">
  let leagueId: string = null
  let userId: string = null
  let isAdmin = true // TODO
  let isAnonymous = true // TODO:
</script>

<style>
  .navbar {
    background-color: var(--color-primary);
    background-image: none;
  }
  .navbar img.logo-small {
    height: 40px;
  }
  .navbar-brand {
    margin-top: -8px;
  }
</style>

<nav class="navbar navbar-expand-md navbar-dark">
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-left">
    <span class="navbar-toggler-icon" />
  </button>
  <a href="/" class="navbar-brand">
    <img
      id="home-link-img"
      class="logo-small"
      src="assets/img/football-white.png"
      alt="110 yards" />
    <label class="sr-only" for="home-link-img">Home</label>
  </a>
  <div id="navbar-left" class="navbar-collapse collapse">
    <div class="nav navbar-nav">
      {#if leagueId}<a href="/league/:leagueId" class="nav-item nav-link">League</a>{/if}

      {#if leagueId && userId}
        <a href="/league/{leagueId}/roster/{userId}" class="nav-item nav-link">My Team</a>
      {/if}

      {#if leagueId}<a href="/league/{leagueId}/players" class="nav-item nav-link">Players</a>{/if}

      <a href="/faq" class="nav-item nav-link">FAQ</a>

      {#if isAdmin}<a href="/admin" class="nav-item nav-link">Admin</a>{/if}
    </div>
    <div class="nav navbar-nav ml-auto">
      {#if isAnonymous}
        <a href="/login" id="login" class="nav-item nav-link">Log in</a>
        <!-- <span class="nav-item navbar-text">{{username}}</span> -->
      {/if}

      {#if !isAnonymous}<a href="/logout" id="logout" class="nav-item nav-link">Log out</a>{/if}
    </div>
  </div>
</nav>

// src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-md navbar-dark">
    <button
      type="button"
      class="navbar-toggler"
      data-toggle="collapse"
      data-target="#navbar-left"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <router-link to="/" class="navbar-brand">
      <img
        class="logo-small"
        src="/assets/img/football-white.png"
        alt="110 yards"
      />
      <label class="sr-only">Home</label>
    </router-link>
    <div
      id="navbar-left"
      class="navbar-collapse collapse"
      :class="visible ? 'show' : null"
      @click="visible = !visible"
    >
      <div class="nav navbar-nav">
        <router-link
          v-if="leagueId"
          class="nav-item nav-link"
          :to="{ name: 'league', params: { leagueId: leagueId } }"
          >League</router-link
        >

        <router-link
          v-if="leagueId && userId"
          class="nav-item nav-link"
          :to="{
            name: 'roster',
            params: { leagueId: leagueId, rosterId: userId },
          }"
          >My Team</router-link
        >

        <router-link
          v-if="leagueId"
          class="nav-item nav-link"
          :to="{ name: 'league-players', params: { leagueId: leagueId } }"
          >Players</router-link
        >

        <router-link class="nav-item nav-link" to="/faq">FAQ</router-link>

        <router-link v-if="isAdmin" class="nav-item nav-link" to="/admin"
          >Admin</router-link
        >
      </div>
      <div class="nav navbar-nav ml-auto">
        <router-link
          id="login"
          v-if="isAnonymous"
          class="nav-item nav-link"
          to="/login"
          >Log in</router-link
        >
        <!-- <span class="nav-item navbar-text">{{username}}</span> -->
        <a
          id="logout"
          v-if="!isAnonymous"
          class="nav-item nav-link"
          href="#"
          @click="logOut"
          >Log out</a
        >
      </div>
    </div>
    <!-- </div> -->
  </nav>
</template>

<style scoped>
.navbar {
  background-color: var(--color-primary);
  background-image: none;
}

.navbar img.logo-small {
  height: 40px;
}

.navbar-brand {
  margin-top: -8px;
}

.navbar-inverse .navbar-nav > li > a {
  color: #cccccc;
}
</style>

<script>
import { auth } from "../modules/firebase"

// TODO: navbar needs to close when I click a link
export default {
  name: "nav-bar",
  data() {
    return {
      visible: false,
      rosterId: null,
    }
  },
  computed: {
    isAnonymous() {
      return this.$store.state.isAnonymous
    },
    username() {
      return this.isAnonymous ? "" : this.$store.state.currentUser.displayName
    },
    userId() {
      return this.isAnonymous ? "" : this.$store.state.uid
    },
    leagueId() {
      return this.$store.state.currentLeagueId
    },
    isAdmin() {
      return this.$store.state.isAdmin
    },
  },
  methods: {
    async logOut() {
      await auth.signOut()
      this.$router.replace("/")
    },
  },
}
</script>
