// src/App.vue
<template>
  <div id="app">
    <nav-bar />
    <div class="container" id="body" :data-version="version">
      <router-view />
      <!-- <throbber /> -->
      <div id="footer">
        <p>&copy; 2020 Michael Dryden</p>
        <p :title="'Version ' + version">Last release {{ lastUpdated }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
#footer {
  padding-top: 2em;
  margin: auto;
  width: 50%;
  text-align: center;
  font-size: small;
  color: gray;
}
</style>

<script>
import NavBar from "./components/NavBar"
// import Throbber from "./components/Throbber";

export default {
  name: "app",
  components: {
    NavBar,
    // Throbber,
  },
  computed: {
    version() {
      return process.env.VUE_APP_VERSION || "0000000"
    },
    lastUpdated() {
      return "a while ago"
    },
  },
  methods: {
    getLastUpdated() {
      return "2020-01-21T04:28+00:00" || new Date()
      //return process.env.VUE_APP_LAST_UPDATED || new Date()
    },
  },
}
</script>

// src/App.svelte
<script type="ts">
  // TODO: move routing into it's own page
  import router from "page"

  import Home from "./components/Home.svelte"
  import About from "./components/About.svelte"

  let page = Home
  let params = null

  router("/", () => (page = Home))
  router("/faq", () => (page = About))
  router("/admin", () => (page = Home))
  router("/login", () => (page = Home))
  router("/league/:leagueId", () => (page = Home))
  router("/league/:leagueId/players", () => (page = Home))
  router("/league/:leagueId/roster/:rosterId", () => (page = Home))
  router.start()

  // end of routing

  import NavBar from "./components/NavBar.svelte"

  export let version = "1.0.0"
  export let lastUpdated = "a while ago"
</script>

<style>
  #footer {
    padding-top: 2em;
    margin: auto;
    width: 50%;
    text-align: center;
    font-size: small;
    color: gray;
  }
</style>

<main>
  <NavBar />

  <svelte:component this={page} {params} />

  <div class="container" id="body" data-version={version}>
    <div id="footer">
      <p>&copy; 2021 Michael Dryden</p>
      <p title="Version {version}">Last release {lastUpdated}</p>
    </div>
  </div>
</main>
